# while deploying to AWS it will look for this file to build container 
# here we are refereing to Dockerfile (production)
version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80" 